### ISSUE TITLE
Package description has <b> </b> shown, but only by Eddy

### ISSUE THREAD

**Issue by pimterry** [donadigo/eddy#135]
Hi,

I'm a package author, rather than an Eddy user as such. That said, one of my users has [reported](https://github.com/httptoolkit/httptoolkit-desktop/issues/58) that when opening my deb package with Eddy, the description is shown wrapped HTML bold tags:

![image](https://user-images.githubusercontent.com/1526883/232808471-e00b54ad-647d-42f3-9cf3-f4b7a6215d97.png)

I can reproduce this myself (installing the latest Eddy code from scratch). I assumed this was a bug in my build process, but I've extracted the deb metadata itself, and these tags aren't present:

```
Package: httptoolkit
Version: 1.12.6
License: AGPL-3.0-or-later
Vendor: contact@httptoolkit.tech
Architecture: amd64
Maintainer: contact@httptoolkit.tech
Installed-Size: 375997
Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libsecret-1-0
Recommends: libappindicator3-1
Section: default
Priority: optional
Homepage: https://httptoolkit.tech
Description: 
  HTTP(S) debugging, development & testing tool
```

This HTML also doesn't show elsewhere, in either gdebi or `dpkg --info` - it only appears in Eddy.

You can download an example deb from https://github.com/httptoolkit/httptoolkit-desktop/releases.

What am I missing? Is there something in my package that's causing this? Any clues much appreciated :smile:.

**Comment by ryonakano** [comment]
I can also confirm this issue by building and installing from the latest source (43a53fdd423e0d342e41b59f9d61ac157e80f088) on elementary OS 7:

![VirtualBox_elementary OS Daily_09_05_2023_20_53_33](https://github.com/donadigo/eddy/assets/26003928/3918dda8-7075-4dae-b98a-ebd7205aa4fe)

Looks like the `<b>` tag is added in Eddy side:

https://github.com/donadigo/eddy/blob/43a53fdd423e0d342e41b59f9d61ac157e80f088/src/PackageRow.vala#L55

and it seems to be displayed due to parse error of `&` in the description in the deb file of httptoolkit-desktop:

```
user@VirtualBox-d8d4863b:~/eddy$ LANG=C com.github.donadigo.eddy

(com.github.donadigo.eddy:10292): Gtk-WARNING **: 20:53:25.001: Failed to set text '<b>HTTP(S) debugging, development & testing tool</b>' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity ? escape ampersand as &amp;

(com.github.donadigo.eddy:10292): Gtk-WARNING **: 20:53:25.002: Failed to set text '<b>HTTP(S) debugging, development & testing tool</b>' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity ? escape ampersand as &amp;
```

I created a PR to fix this issue on Eddy side: #136
