### ISSUE TITLE
No feedback when PackageKit is busy

### ISSUE THREAD

**Issue by cassidyjames** [donadigo/eddy#6]
If I try to install a .deb via any method while PackageKit is busy doing something else (i.e. AppCenter is running updates), there's no feedback in Eddy, and it doesn't queue up the installation.

**Comment by tommystanton** [comment]
I believe this would be similar...I just used Eddy to install `google-chrome-stable`.  I hadn't realized I had a `sudo aptitude` process running in another shell (which was holding a lock on APT).

Because of the APT lock, Eddy silently failed, as far as I could tell (Eddy reported "Installed," though the package was not actually installed).

Quitting the `sudo aptitude` process and using Eddy again worked fine. :ok_hand:

**Comment by donadigo** [comment]
Fixed by https://github.com/donadigo/eddy/commit/96cdc8f771f56c4506f240111b8b02663496b3e1.
